export const DirectoryActionTypes = {
  GET_CATEGORIES_LOAD: "GET_CATEGORIES_LOAD",
  GET_CATEGORIES_ERROR: "GET_CATEGORIES_ERROR",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_IDLE: "GET_CATEGORIES_IDLE",
};
