export const ShopActionTypes = {
  GET_PRODUCT_LOAD: "GET_PRODUCT_LOAD",
  GET_PRODUCT_ERROR: "GET_PRODUCT_ERROR",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_IDLE: "GET_PRODUCT_IDLE",
};
